{
  "openapi": "3.0.0",
  "info": {
    "title": "Beverage E-commerce API",
    "version": "1.0.0",
    "description": "API for managing beverages, labels, ingredients, container types, and unit measures in a beverage e-commerce platform."
  },
  "servers": [
    {
      "url": "https://api.beverage-ecommerce.com/v2"
    }
  ],
  "security": [
    {
      "BearerAuth": [
        "read:beverages",
        "write:beverages",
        "read:brands",
        "write:brands",
        "read:labels",
        "write:labels",
        "read:ingredients",
        "write:ingredients",
        "read:container-types",
        "write:container-types"
      ]
    }
  ],
  "tags": [
    {
      "name": "beverage",
      "description": "Operations related to beverages"
    },
    {
      "name": "label",
      "description": "Operations related to labels"
    },
    {
      "name": "brand",
      "description": "Operations related to brands"
    },
    {
      "name": "container-type",
      "description": "Operations related to container types"
    },
    {
      "name": "ingredient",
      "description": "Operations related to ingredients"
    }
  ],
  "paths": {
    "/beverages": {
      "get": {
        "tags": [
          "beverage"
        ],
        "summary": "Retrieve all beverages",
        "description": "Retrieves a list of all beverages.",
        "operationId": "getBeverages",
        "security": [
          {
            "BearerAuth": [
              "read:beverages"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "beverage"
        ],
        "summary": "Create a new beverage",
        "description": "Creates a new beverage.",
        "operationId": "createBeverage",
        "security": [
          {
            "BearerAuth": [
              "write:beverages"
            ]
          }
        ]
      }
    },
    "/beverages/{id}": {
      "get": {
        "tags": [
          "beverage"
        ],
        "summary": "Retrieve a beverage by ID",
        "description": "Retrieves details of a specific beverage.",
        "operationId": "getBeverageById",
        "security": [
          {
            "BearerAuth": [
              "read:beverages"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "beverage"
        ],
        "summary": "Update a beverage",
        "description": "Create or Replace an existing beverage.",
        "operationId": "replaceBeverage",
        "security": [
          {
            "BearerAuth": [
              "write:beverages",
              "read:beverages"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "beverage"
        ],
        "summary": "Partially update a beverage",
        "description": "Update an existing beverage.",
        "operationId": "updateBeverage",
        "security": [
          {
            "BearerAuth": [
              "write:beverages",
              "read:beverages"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "beverage"
        ],
        "summary": "Delete a beverage",
        "description": "Deletes a beverage.",
        "operationId": "deleteBeverage",
        "security": [
          {
            "BearerAuth": [
              "write:beverages",
              "read:beverages"
            ]
          }
        ]
      }
    },
    "/beverages/{id}/labels": {
      "get": {
        "tags": [
          "label"
        ],
        "summary": "Retrieve all labels",
        "description": "Retrieves a list of all labels.",
        "operationId": "getLabels",
        "security": [
          {
            "BearerAuth": [
              "read:labels"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "label"
        ],
        "summary": "Create a new label",
        "description": "Creates a new label.",
        "operationId": "createLabel",
        "security": [
          {
            "BearerAuth": [
              "write:labels",
              "read:labels"
            ]
          }
        ]
      }
    },
    "/beverages/{beverageId}/labels/{id}": {
      "get": {
        "tags": [
          "label"
        ],
        "summary": "Retrieve a label by ID and beverage ID",
        "description": "Retrieves details of a specific label.",
        "operationId": "getLabelById",
        "security": [
          {
            "BearerAuth": [
              "read:labels"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "label"
        ],
        "summary": "Update a label",
        "description": "Create or Replace an existing label.",
        "operationId": "replaceLabel",
        "security": [
          {
            "BearerAuth": [
              "write:labels",
              "read:labels"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "label"
        ],
        "summary": "Partially update a label",
        "description": "Update existing label.",
        "operationId": "updateLabel",
        "security": [
          {
            "BearerAuth": [
              "write:labels",
              "read:labels"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "label"
        ],
        "summary": "Delete a label",
        "description": "Deletes a label.",
        "operationId": "deleteLabel",
        "security": [
          {
            "BearerAuth": [
              "write:labels",
              "read:labels"
            ]
          }
        ]
      }
    },
    "/brands": {
      "get": {
        "tags": [
          "brand"
        ],
        "summary": "Retrieve all brand",
        "description": "Retrieves a list of all brands.",
        "operationId": "getBrands",
        "security": [
          {
            "BearerAuth": [
              "read:brands"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "brand"
        ],
        "summary": "Create a new brand",
        "description": "Creates a new brand.",
        "operationId": "createBrand",
        "security": [
          {
            "BearerAuth": [
              "write:brands",
              "read:brands"
            ]
          }
        ]
      }
    },
    "/brands/{id}": {
      "get": {
        "tags": [
          "brand"
        ],
        "summary": "Retrieve a brand by ID",
        "description": "Retrieves details of a specific brand.",
        "operationId": "getBrandById",
        "security": [
          {
            "BearerAuth": [
              "read:brands"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "brand"
        ],
        "summary": "Update a brand",
        "description": "Create or replace an existing brand.",
        "operationId": "replaceBrand",
        "security": [
          {
            "BearerAuth": [
              "write:brands",
              "read:brands"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "brand"
        ],
        "summary": "Partially update a brand",
        "description": "Update an existing brand.",
        "operationId": "updateBrand",
        "security": [
          {
            "BearerAuth": [
              "write:brands",
              "read:brands"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "brand"
        ],
        "summary": "Delete a brand",
        "description": "Deletes a brand.",
        "operationId": "deleteBrand",
        "security": [
          {
            "BearerAuth": [
              "write:brands",
              "read:brands"
            ]
          }
        ]
      }
    },
    "/ingredients": {
      "get": {
        "tags": [
          "ingredient"
        ],
        "summary": "Retrieve all ingredients",
        "description": "Retrieves a list of all ingredients.",
        "operationId": "getIngredients",
        "security": [
          {
            "BearerAuth": [
              "read:ingredients"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "ingredient"
        ],
        "summary": "Create a new ingredient",
        "description": "Creates a new ingredient.",
        "operationId": "createIngredient",
        "security": [
          {
            "BearerAuth": [
              "write:ingredients",
              "read:ingredients"
            ]
          }
        ]
      }
    },
    "/ingredients/{id}": {
      "get": {
        "tags": [
          "ingredient"
        ],
        "summary": "Retrieve an ingredient by ID",
        "description": "Retrieves details of a specific ingredient.",
        "operationId": "getIngredientById",
        "security": [
          {
            "BearerAuth": [
              "read:ingredients"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "ingredient"
        ],
        "summary": "Update an ingredient",
        "description": "Create or Replace an existing ingredient.",
        "operationId": "replaceIngredient",
        "security": [
          {
            "BearerAuth": [
              "write:ingredients",
              "read:ingredients"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ingredient"
        ],
        "summary": "Update an ingredient",
        "description": "Updates an existing ingredient.",
        "operationId": "updateIngredient",
        "security": [
          {
            "BearerAuth": [
              "write:ingredients",
              "read:ingredients"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ingredient"
        ],
        "summary": "Delete an ingredient",
        "description": "Deletes an ingredient.",
        "operationId": "deleteIngredient",
        "security": [
          {
            "BearerAuth": [
              "write:ingredients",
              "read:ingredients"
            ]
          }
        ]
      }
    },
    "/container-types": {
      "get": {
        "tags": [
          "container-type"
        ],
        "summary": "Retrieve all container types",
        "description": "Retrieves a list of all container types.",
        "operationId": "getContainerTypes",
        "security": [
          {
            "BearerAuth": [
              "read:container-types"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "container-type"
        ],
        "summary": "Create a new container type",
        "description": "Creates a new container type.",
        "operationId": "createContainerType",
        "security": [
          {
            "BearerAuth": [
              "write:container-types",
              "read:container-types"
            ]
          }
        ]
      }
    },
    "/container-types/{id}": {
      "get": {
        "tags": [
          "container-type"
        ],
        "summary": "Retrieve a container type by ID",
        "description": "Retrieves details of a specific container type.",
        "operationId": "getContainerTypeById",
        "security": [
          {
            "BearerAuth": [
              "read:container-types"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "container-type"
        ],
        "summary": "Update a container type",
        "description": "Create or replace a container type.",
        "operationId": "putContainerType",
        "security": [
          {
            "BearerAuth": [
              "write:container-types",
              "read:container-types"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "container-type"
        ],
        "summary": "Update a container type",
        "description": "Updates an existing container type.",
        "operationId": "updateContainerType",
        "security": [
          {
            "BearerAuth": [
              "write:container-types",
              "read:container-types"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "container-type"
        ],
        "summary": "Delete a container type",
        "description": "Deletes a container type.",
        "operationId": "deleteContainerType",
        "security": [
          {
            "BearerAuth": [
              "write:container-types",
              "read:container-types"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}