# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BrandsIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, description: str=None):  # noqa: E501
        """BrandsIdBody - a model defined in Swagger

        :param name: The name of this BrandsIdBody.  # noqa: E501
        :type name: str
        :param description: The description of this BrandsIdBody.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description'
        }
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'BrandsIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The brands_id_body of this BrandsIdBody.  # noqa: E501
        :rtype: BrandsIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this BrandsIdBody.


        :return: The name of this BrandsIdBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BrandsIdBody.


        :param name: The name of this BrandsIdBody.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this BrandsIdBody.


        :return: The description of this BrandsIdBody.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this BrandsIdBody.


        :param description: The description of this BrandsIdBody.
        :type description: str
        """

        self._description = description
