# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ContainertypesIdBody1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, volume: float=None):  # noqa: E501
        """ContainertypesIdBody1 - a model defined in Swagger

        :param type: The type of this ContainertypesIdBody1.  # noqa: E501
        :type type: str
        :param volume: The volume of this ContainertypesIdBody1.  # noqa: E501
        :type volume: float
        """
        self.swagger_types = {
            'type': str,
            'volume': float
        }

        self.attribute_map = {
            'type': 'type',
            'volume': 'volume'
        }
        self._type = type
        self._volume = volume

    @classmethod
    def from_dict(cls, dikt) -> 'ContainertypesIdBody1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The containertypes_id_body_1 of this ContainertypesIdBody1.  # noqa: E501
        :rtype: ContainertypesIdBody1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this ContainertypesIdBody1.


        :return: The type of this ContainertypesIdBody1.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ContainertypesIdBody1.


        :param type: The type of this ContainertypesIdBody1.
        :type type: str
        """

        self._type = type

    @property
    def volume(self) -> float:
        """Gets the volume of this ContainertypesIdBody1.


        :return: The volume of this ContainertypesIdBody1.
        :rtype: float
        """
        return self._volume

    @volume.setter
    def volume(self, volume: float):
        """Sets the volume of this ContainertypesIdBody1.


        :param volume: The volume of this ContainertypesIdBody1.
        :type volume: float
        """

        self._volume = volume
