# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IngredientsIdBody1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, allergen_info: str=None):  # noqa: E501
        """IngredientsIdBody1 - a model defined in Swagger

        :param name: The name of this IngredientsIdBody1.  # noqa: E501
        :type name: str
        :param allergen_info: The allergen_info of this IngredientsIdBody1.  # noqa: E501
        :type allergen_info: str
        """
        self.swagger_types = {
            'name': str,
            'allergen_info': str
        }

        self.attribute_map = {
            'name': 'name',
            'allergen_info': 'allergen_info'
        }
        self._name = name
        self._allergen_info = allergen_info

    @classmethod
    def from_dict(cls, dikt) -> 'IngredientsIdBody1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ingredients_id_body_1 of this IngredientsIdBody1.  # noqa: E501
        :rtype: IngredientsIdBody1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this IngredientsIdBody1.


        :return: The name of this IngredientsIdBody1.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this IngredientsIdBody1.


        :param name: The name of this IngredientsIdBody1.
        :type name: str
        """

        self._name = name

    @property
    def allergen_info(self) -> str:
        """Gets the allergen_info of this IngredientsIdBody1.


        :return: The allergen_info of this IngredientsIdBody1.
        :rtype: str
        """
        return self._allergen_info

    @allergen_info.setter
    def allergen_info(self, allergen_info: str):
        """Sets the allergen_info of this IngredientsIdBody1.


        :param allergen_info: The allergen_info of this IngredientsIdBody1.
        :type allergen_info: str
        """

        self._allergen_info = allergen_info
