# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.beverage import Beverage  # noqa: F401,E501
from swagger_server.models.pagination_links import PaginationLinks  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, beverages: List[Beverage]=None, links: List[PaginationLinks]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param beverages: The beverages of this InlineResponse200.  # noqa: E501
        :type beverages: List[Beverage]
        :param links: The links of this InlineResponse200.  # noqa: E501
        :type links: List[PaginationLinks]
        """
        self.swagger_types = {
            'beverages': List[Beverage],
            'links': List[PaginationLinks]
        }

        self.attribute_map = {
            'beverages': 'beverages',
            'links': 'links'
        }
        self._beverages = beverages
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def beverages(self) -> List[Beverage]:
        """Gets the beverages of this InlineResponse200.


        :return: The beverages of this InlineResponse200.
        :rtype: List[Beverage]
        """
        return self._beverages

    @beverages.setter
    def beverages(self, beverages: List[Beverage]):
        """Sets the beverages of this InlineResponse200.


        :param beverages: The beverages of this InlineResponse200.
        :type beverages: List[Beverage]
        """

        self._beverages = beverages

    @property
    def links(self) -> List[PaginationLinks]:
        """Gets the links of this InlineResponse200.


        :return: The links of this InlineResponse200.
        :rtype: List[PaginationLinks]
        """
        return self._links

    @links.setter
    def links(self, links: List[PaginationLinks]):
        """Sets the links of this InlineResponse200.


        :param links: The links of this InlineResponse200.
        :type links: List[PaginationLinks]
        """

        self._links = links
