openapi: 3.0.0
info:
  description: API for managing beverages, labels, ingredients, container types, and
    unit measures in a beverage e-commerce platform.
  title: Beverage E-commerce API
  version: 1.0.0
servers:
- url: https://api.beverage-ecommerce.com/v2
security:
- BearerAuth:
  - read:beverages
  - write:beverages
  - read:brands
  - write:brands
  - read:labels
  - write:labels
  - read:ingredients
  - write:ingredients
  - read:container-types
  - write:container-types
tags:
- description: Operations related to beverages
  name: beverage
- description: Operations related to labels
  name: label
- description: Operations related to brands
  name: brand
- description: Operations related to container types
  name: container-type
- description: Operations related to ingredients
  name: ingredient
paths:
  /beverages:
    get:
      description: Retrieves a list of all beverages.
      operationId: get_beverages
      security:
      - BearerAuth:
        - read:beverages
      summary: Retrieve all beverages
      tags:
      - beverage
      x-openapi-router-controller: swagger_server.controllers.beverage_controller
      x-accepts: application/json
    post:
      description: Creates a new beverage.
      operationId: create_beverage
      security:
      - BearerAuth:
        - write:beverages
      summary: Create a new beverage
      tags:
      - beverage
      x-openapi-router-controller: swagger_server.controllers.beverage_controller
      x-contentType: application/json
      x-accepts: application/json
  /beverages/{id}:
    delete:
      description: Deletes a beverage.
      operationId: delete_beverage
      security:
      - BearerAuth:
        - write:beverages
        - read:beverages
      summary: Delete a beverage
      tags:
      - beverage
      x-openapi-router-controller: swagger_server.controllers.beverage_controller
      x-accepts: application/json
    get:
      description: Retrieves details of a specific beverage.
      operationId: get_beverage_by_id
      security:
      - BearerAuth:
        - read:beverages
      summary: Retrieve a beverage by ID
      tags:
      - beverage
      x-openapi-router-controller: swagger_server.controllers.beverage_controller
      x-accepts: application/json
    patch:
      description: Update an existing beverage.
      operationId: update_beverage
      security:
      - BearerAuth:
        - write:beverages
        - read:beverages
      summary: Partially update a beverage
      tags:
      - beverage
      x-openapi-router-controller: swagger_server.controllers.beverage_controller
      x-contentType: application/json
      x-accepts: application/json
    put:
      description: Create or Replace an existing beverage.
      operationId: replace_beverage
      security:
      - BearerAuth:
        - write:beverages
        - read:beverages
      summary: Update a beverage
      tags:
      - beverage
      x-openapi-router-controller: swagger_server.controllers.beverage_controller
      x-contentType: application/json
      x-accepts: application/json
  /beverages/{id}/labels:
    get:
      description: Retrieves a list of all labels.
      operationId: get_labels
      security:
      - BearerAuth:
        - read:labels
      summary: Retrieve all labels
      tags:
      - label
      x-openapi-router-controller: swagger_server.controllers.label_controller
      x-accepts: application/json
    post:
      description: Creates a new label.
      operationId: create_label
      security:
      - BearerAuth:
        - write:labels
        - read:labels
      summary: Create a new label
      tags:
      - label
      x-openapi-router-controller: swagger_server.controllers.label_controller
      x-contentType: application/json
      x-accepts: application/json
  /beverages/{beverageId}/labels/{id}:
    delete:
      description: Deletes a label.
      operationId: delete_label
      security:
      - BearerAuth:
        - write:labels
        - read:labels
      summary: Delete a label
      tags:
      - label
      x-openapi-router-controller: swagger_server.controllers.label_controller
      x-accepts: application/json
    get:
      description: Retrieves details of a specific label.
      operationId: get_label_by_id
      security:
      - BearerAuth:
        - read:labels
      summary: Retrieve a label by ID and beverage ID
      tags:
      - label
      x-openapi-router-controller: swagger_server.controllers.label_controller
      x-accepts: application/json
    patch:
      description: Update existing label.
      operationId: update_label
      security:
      - BearerAuth:
        - write:labels
        - read:labels
      summary: Partially update a label
      tags:
      - label
      x-openapi-router-controller: swagger_server.controllers.label_controller
      x-contentType: application/json
      x-accepts: application/json
    put:
      description: Create or Replace an existing label.
      operationId: replace_label
      security:
      - BearerAuth:
        - write:labels
        - read:labels
      summary: Update a label
      tags:
      - label
      x-openapi-router-controller: swagger_server.controllers.label_controller
      x-contentType: application/json
      x-accepts: application/json
  /brands:
    get:
      description: Retrieves a list of all brands.
      operationId: get_brands
      security:
      - BearerAuth:
        - read:brands
      summary: Retrieve all brand
      tags:
      - brand
      x-openapi-router-controller: swagger_server.controllers.brand_controller
      x-accepts: application/json
    post:
      description: Creates a new brand.
      operationId: create_brand
      security:
      - BearerAuth:
        - write:brands
        - read:brands
      summary: Create a new brand
      tags:
      - brand
      x-openapi-router-controller: swagger_server.controllers.brand_controller
      x-contentType: application/json
      x-accepts: application/json
  /brands/{id}:
    delete:
      description: Deletes a brand.
      operationId: delete_brand
      security:
      - BearerAuth:
        - write:brands
        - read:brands
      summary: Delete a brand
      tags:
      - brand
      x-openapi-router-controller: swagger_server.controllers.brand_controller
      x-accepts: application/json
    get:
      description: Retrieves details of a specific brand.
      operationId: get_brand_by_id
      security:
      - BearerAuth:
        - read:brands
      summary: Retrieve a brand by ID
      tags:
      - brand
      x-openapi-router-controller: swagger_server.controllers.brand_controller
      x-accepts: application/json
    patch:
      description: Update an existing brand.
      operationId: update_brand
      security:
      - BearerAuth:
        - write:brands
        - read:brands
      summary: Partially update a brand
      tags:
      - brand
      x-openapi-router-controller: swagger_server.controllers.brand_controller
      x-contentType: application/json
      x-accepts: application/json
    put:
      description: Create or replace an existing brand.
      operationId: replace_brand
      security:
      - BearerAuth:
        - write:brands
        - read:brands
      summary: Update a brand
      tags:
      - brand
      x-openapi-router-controller: swagger_server.controllers.brand_controller
      x-contentType: application/json
      x-accepts: application/json
  /ingredients:
    get:
      description: Retrieves a list of all ingredients.
      operationId: get_ingredients
      security:
      - BearerAuth:
        - read:ingredients
      summary: Retrieve all ingredients
      tags:
      - ingredient
      x-openapi-router-controller: swagger_server.controllers.ingredient_controller
      x-accepts: application/json
    post:
      description: Creates a new ingredient.
      operationId: create_ingredient
      security:
      - BearerAuth:
        - write:ingredients
        - read:ingredients
      summary: Create a new ingredient
      tags:
      - ingredient
      x-openapi-router-controller: swagger_server.controllers.ingredient_controller
      x-contentType: application/json
      x-accepts: application/json
  /ingredients/{id}:
    delete:
      description: Deletes an ingredient.
      operationId: delete_ingredient
      security:
      - BearerAuth:
        - write:ingredients
        - read:ingredients
      summary: Delete an ingredient
      tags:
      - ingredient
      x-openapi-router-controller: swagger_server.controllers.ingredient_controller
      x-accepts: application/json
    get:
      description: Retrieves details of a specific ingredient.
      operationId: get_ingredient_by_id
      security:
      - BearerAuth:
        - read:ingredients
      summary: Retrieve an ingredient by ID
      tags:
      - ingredient
      x-openapi-router-controller: swagger_server.controllers.ingredient_controller
      x-accepts: application/json
    patch:
      description: Updates an existing ingredient.
      operationId: update_ingredient
      security:
      - BearerAuth:
        - write:ingredients
        - read:ingredients
      summary: Update an ingredient
      tags:
      - ingredient
      x-openapi-router-controller: swagger_server.controllers.ingredient_controller
      x-contentType: application/json
      x-accepts: application/json
    put:
      description: Create or Replace an existing ingredient.
      operationId: replace_ingredient
      security:
      - BearerAuth:
        - write:ingredients
        - read:ingredients
      summary: Update an ingredient
      tags:
      - ingredient
      x-openapi-router-controller: swagger_server.controllers.ingredient_controller
      x-contentType: application/json
      x-accepts: application/json
  /container-types:
    get:
      description: Retrieves a list of all container types.
      operationId: get_container_types
      security:
      - BearerAuth:
        - read:container-types
      summary: Retrieve all container types
      tags:
      - container-type
      x-openapi-router-controller: swagger_server.controllers.container_type_controller
      x-accepts: application/json
    post:
      description: Creates a new container type.
      operationId: create_container_type
      security:
      - BearerAuth:
        - write:container-types
        - read:container-types
      summary: Create a new container type
      tags:
      - container-type
      x-openapi-router-controller: swagger_server.controllers.container_type_controller
      x-contentType: application/json
      x-accepts: application/json
  /container-types/{id}:
    delete:
      description: Deletes a container type.
      operationId: delete_container_type
      security:
      - BearerAuth:
        - write:container-types
        - read:container-types
      summary: Delete a container type
      tags:
      - container-type
      x-openapi-router-controller: swagger_server.controllers.container_type_controller
      x-accepts: application/json
    get:
      description: Retrieves details of a specific container type.
      operationId: get_container_type_by_id
      security:
      - BearerAuth:
        - read:container-types
      summary: Retrieve a container type by ID
      tags:
      - container-type
      x-openapi-router-controller: swagger_server.controllers.container_type_controller
      x-accepts: application/json
    patch:
      description: Updates an existing container type.
      operationId: update_container_type
      security:
      - BearerAuth:
        - write:container-types
        - read:container-types
      summary: Update a container type
      tags:
      - container-type
      x-openapi-router-controller: swagger_server.controllers.container_type_controller
      x-contentType: application/json
      x-accepts: application/json
    put:
      description: Create or replace a container type.
      operationId: put_container_type
      security:
      - BearerAuth:
        - write:container-types
        - read:container-types
      summary: Update a container type
      tags:
      - container-type
      x-openapi-router-controller: swagger_server.controllers.container_type_controller
      x-contentType: application/json
      x-accepts: application/json
components:
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_BearerAuth

